AddonId: JosefNemec_Library_ItchIo
Type: GameLibrary
IconUrl: https://raw.githubusercontent.com/CanRanBan/PlayniteExtensionFork-Extensions-Common/main/Source/Library/itch.io/Resources/ItchIoLibraryIcon.ico
Name: itch.io Library
ShortDescription: Imports games available on PC from itch.io.
Author: Josef Nemec
SourceUrl: https://github.com/CanRanBan/PlayniteExtensionFork-Extensions-Common
Links:
    GitHub (Source code): https://github.com/CanRanBan/PlayniteExtensionFork-Extensions-Common
    Wiki (Introduction and Help): https://github.com/CanRanBan/PlayniteExtensionFork-Extensions-Common/wiki
    itch.io App: https://itch.io/app
    Playnite Discord (#extensions-support): https://discord.com/channels/365863063296933888/808419165311467630
    Issues (Feature requests and Bugs): https://github.com/CanRanBan/PlayniteExtensionFork-Extensions-Common/issues
InstallerManifestUrl: https://raw.githubusercontent.com/CanRanBan/PlayniteExtensionFork-Extensions-Common/main/Manifests/PackageInstaller/JosefNemec_Library_ItchIo.yaml
Description: The "itch.io Library" Playnite extension imports games available on PC from itch.io. It optionally requires "itch.io App" for additional features. Availability and game selection might differ by country.
Tags: ["Josef Nemec", "Library", "itch", "io"]